# Generated by Django 3.2.9 on 2021-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='Toto'),
            preserve_default=False,
        ),
    ]
